### ISSUE TITLE
Getting code 500 when trying to login

### ISSUE THREAD

**Issue by aleksejlopasov** [GoogleCloudDataproc/jupyterhub-dataprocspawner#24]
Another issue detected while logging in to JH.
<img width="1241" alt="Screen Shot 2020-08-26 at 3 41 19 PM" src="https://user-images.githubusercontent.com/20720498/91304750-aa904d00-e7b2-11ea-9c03-5f12c33bb59c.png">
Here are logs from docker container:
```
[I 2020-08-26 12:38:20.673 JupyterHub base:742] User logged in: admin
[E 2020-08-26 12:38:20.676 JupyterHub web:1792] Uncaught exception POST /hub/login?next= (::ffff:213.110.141.242)
    HTTPServerRequest(protocol='http', host='35.222.13.252:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:213.110.141.242')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 150, in post
        self.redirect(self.get_next_url(user))
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 649, in get_next_url
        if user.spawner.active:
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 340, in spawner
        return self.spawners['']
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 187, in __getitem__
        self[key] = self.spawner_factory(key)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 333, in _new_spawner
        spawner = spawner_class(**spawn_kwargs)
      File "/usr/local/lib/python3.6/dist-packages/dataprocspawner/spawner.py", line 237, in __init__
        address=f'{self.region}-dataproc.googleapis.com:443'))
    TypeError: __init__() got an unexpected keyword argument 'address'

[E 2020-08-26 12:38:20.684 JupyterHub log:173] {
      "X-Forwarded-Host": "35.222.13.252:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:213.110.141.242",
      "Accept-Language": "en-US,en;q=0.9,ru;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://35.222.13.252:8000/hub/login?next=",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded",
      "Origin": "http://35.222.13.252:8000",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "Content-Length": "24",
      "Connection": "close",
      "Host": "35.222.13.252:8000"
    }
[E 2020-08-26 12:38:20.688 JupyterHub log:181] 500 POST /hub/login?next= (admin@::ffff:213.110.141.242) 16.77ms
```
This still blocks me from testing the code of my PR

**Comment by aleksejlopasov** [comment]
Fixed with https://github.com/GoogleCloudDataproc/jupyterhub-dataprocspawner/pull/25
